### ISSUE TITLE
Adding Uniqueidentifiers to SqlValues

### ISSUE THREAD

**Issue by rommsen** [Zaid-Ajaj/DustyTables#1]
Hey Zaid,

I am using the library to add some test data to my database. Works nice so far, thanks!

Would it be possible that you could add the type Uniqueidentifier to the SqlValue DU. This would help alot.

Thanks

**Comment by Zaid-Ajaj** [comment]
Hi Roman, I am glad to hear that! I've added the uniqueidentifier value and pushed it to nuget (v0.4.0), it should be available soon :smile:

**Comment by Zaid-Ajaj** [comment]
Scratch that, I forgot to add `Sql.readUniqueIdentifier` 😅 it's actually v0.5.0 now hahah

**Comment by rommsen** [comment]
Awesome. Works perfectly. Thanks!
