### ISSUE TITLE
Add executeTransactionTask and executeTransactionSafeTask

### ISSUE THREAD

**Issue by Elonon** [Zaid-Ajaj/DustyTables#2]
**Is your feature request related to a problem? Please describe.**
I like your library and would like to run Transactions but since I'm already using TaskBuilder.fs I'd like to use Tasks directly and not  wrap async.

**Describe the solution you'd like**
I would like two more functions added, `executeTransactionTask` that throws and `executeTransactionSafeTask` that returns `Result<>`.

**Describe alternatives you've considered**
The alternative is to wrap `executeTransactionAsync` with try/catch and `Async.StartAsTask`

**Additional context**
I am willing to submit a PR if you'd like.

**Comment by Zaid-Ajaj** [comment]
Hello @Elonon, this is a good feature to add. It would be really awesome if you send a PR :smile:
