### ISSUE TITLE
Rollback transaction

### ISSUE THREAD

**Issue by AlbertoDePena** [Zaid-Ajaj/DustyTables#20]
Do you think the `executeTransaction` and `executeTransactionAsync` methods should roll back the transaction when an error occurs? Unless the disposing of the `Connection` does the trick?

**Comment by Zaid-Ajaj** [comment]
Well, the transaction doesn't commit unless everything works as expected, so is the rollback necessary in this case?

**Comment by AlbertoDePena** [comment]
That is a great question... I'll have to do some digging into it! =)
