### ISSUE TITLE
Please consider replacing System.Data.SqlClient with Microsoft.Data.SqlClient

### ISSUE THREAD

**Issue by Elonon** [Zaid-Ajaj/DustyTables#4]
**Is your feature request related to a problem? Please describe.**
[Microsoft.Data.SqlClient](https://github.com/dotnet/SqlClient) is the new .NET library for SQL Server. It includes new features and works better in Core in some scenarios. In my particular case Azure Functions v3. I believe it supports all the frameworks you target.

**Describe the solution you'd like**
This would be a breaking change, so I don't know if you would want to split libraries or just put a note on the readme. The change requires only changing your dep in Paket and changing one [open statement](https://github.com/Zaid-Ajaj/DustyTables/blob/3d256f23fb4c1acaee134ef43e5d8fdf1581daad/src/DustyTables/Sql.fs#L29).

**Describe alternatives you've considered**
As I said above, you could two create nuget packages if cutting it off feels too extreme.

**Additional context**
[Here is a blog post from the initial announcement](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/).

It's out of preview now.

**Comment by Zaid-Ajaj** [comment]
Hello @Elonon thanks a lot for the suggestion, I plan to get back to this package and update it's dependencies and tests (maybe add some nice helper functions along the way). It the update urgent? I will try to update the package in this coming weekend or next week!

**Comment by Elonon** [comment]
Nope, no rush. 

If you're doing code changes, please also consider changing [this line](https://github.com/Zaid-Ajaj/DustyTables/blob/3d256f23fb4c1acaee134ef43e5d8fdf1581daad/src/DustyTables/Sql.fs#L30) to 
```fsharp
open FSharp.Control.Tasks.V2.ContextInsensitive
```

I can open a separate issue if you want and also provide you with article links, but the tl;dr is that V2 is the better version from TaskBuilder.fs and ContextInsensitive is the recommended best practice for a library. (It translates to ```ConfigureAwait(false)```)

**Comment by Zaid-Ajaj** [comment]
I will keep it in mind, no need for a separate issue, thanks a lot :pray:

**Comment by Elonon** [comment]
Friendly bump 😎

**Comment by Zaid-Ajaj** [comment]
Sorry for the delay @Elonon, trying to find a good time slot to get into this again. I will try to publish a new version over the weekend. 

> You could help me out if you can and send a PR with the required changes, I will be happy to publish it afterwards right away :smile:

**Comment by Elonon** [comment]
No problem, I didn't think you wanted a PR this time. Pushing up changes now.

**Comment by Zaid-Ajaj** [comment]
PRs are always welsome :heart:

**Comment by Elonon** [comment]
Thanks for merging the project 🎉, please don't forget to publish it 😉

**Comment by Zaid-Ajaj** [comment]
Hello @Elonon, I have published the new version with the updates as of  v1.2.0 and it should be available soon on nuget :smile:
