### ISSUE TITLE
Support for table-valued parameters

### ISSUE THREAD

**Issue by nozzlegear** [Zaid-Ajaj/DustyTables#6]
**Is your feature request related to a problem? Please describe.**
Hello! I'm looking for a way to use [table-valued parameters](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/table-valued-parameters) with this package. TVPs let you use tables as parameters for stored procedures. For example, if I have a one-to-many relationship, I could use a TVP and a stored procedure to create the parent relationship and multiple children all in one function. 

As it stands now, it looks like we're limited to only using the parameter types in the `SqlValue` DU. 

**Describe the solution you'd like**

I've played around with this package and have come up with a rough solution that works, although I don't think it's ideal yet for a couple reasons I'll get to below. Here's what my changes look like:

```fs
type SqlValue =
    | TinyInt of uint8
    | Smallint of int16
    | Int of int
    | Bigint of int64
    | String of string
    | DateTime of DateTime
    | DateTimeOffset of DateTimeOffset
    | Bool of bool
    | Float of double
    | Decimal of decimal
    | Binary of byte[]
    | UniqueIdentifier of Guid
    | Null
    | Table of TableValuedParameter
and TableValuedParameter = string * string list * list<list<SqlValue>>
```

For the `TableValuedParameter` type, the first string is the SQL type name (e.g. "MyCustomTableType"). The second string list is the list of columns in the custom table.

I also added a convenience module for assembling a `TableValuedParameter`:

```fs
module SqlTvp = 
    let typeName str : TableValuedParameter =
        str, [], []

    let columns cols ((typeName, _, rows) : TableValuedParameter) : TableValuedParameter =
        typeName, cols, rows

    let rows rows ((typeName, cols, _) : TableValuedParameter) : TableValuedParameter =
        typeName, cols, rows

    let addRow row ((typeName, cols, rows) : TableValuedParameter) : TableValuedParameter =
        typeName, cols, rows @ [row]
```

And you can combine it all with a stored procedure like this:

```fs
let tvp = 
    SqlTvp.typeName "MyCustomTableType"
    |> SqlTvp.columns ["FirstName"; "LastName"; "DOB"]
    |> SqlTvp.addRow ["John"; "Doe"; someDate]
    |> SqlTvp.addRow ["Jane"; "Doe"; someDate]

Sql.connect connStr
|> Sql.storedProcedure "sp_myStoredProc"
|> Sql.parameters
    [ "@foo", SqlValue.Int 1
      "@bar", SqlValue.Int 2
      "@baz", SqlValue.Table tvp ]
```

Behind the scenes, the `populate` function is changed to take the `SqlValue.Table` case and turn it into a .NET DataTable:

```fs
//...
| SqlValue.Table (typeName, cols, rows) -> 
    let dataTable = new DataTable()

    for col in cols do 
        dataTable.Columns.Add col |> ignore

    for row in rows do 
        let rowValues = row |> List.map getParamValue |> Array.ofList
        dataTable.Rows.Add rowValues |> ignore 

    let tableParameter = cmd.Parameters.AddWithValue(paramName, dataTable)
    // TypeName must be set to the custom SQL tvp type 
    tableParameter.TypeName <- typeName
    // SqlDbType must be set to Structured for a TVP parameter
    tableParameter.SqlDbType <- SqlDbType.Structured

```

So this works pretty well, but I don't think it's 100% ideal at the moment. Chiefly that's because, as far as I understand, table-valued parameters _only_ work with stored procedures; they can't be used in regular SQL queries/commands. That means the `SqlValue` type suddenly has a case that only applies in one scenario and is completely invalid for others, which could lead to confusion and exceptions.

On top of that, you can't nest TVPs (as far as I know), so making the `SqlValue` type "recursive" with the Table case can lead to more confusion. 

**Describe alternatives you've considered**

I think an easier alternative is just adding a `Custom` case to the `SqlValue` DU, perhaps with a callback function that can configure the parameter (so we can set the `param.TypeName` and `param.SqlDbType` props).

```fs
type SqlValue =
    | TinyInt of uint8
    | Smallint of int16
    | Int of int
    | Bigint of int64
    | String of string
    | DateTime of DateTime
    | DateTimeOffset of DateTimeOffset
    | Bool of bool
    | Float of double
    | Decimal of decimal
    | Binary of byte[]
    | UniqueIdentifier of Guid
    | Null
    | Custom of obj * (SqlParameter -> unit)
```

And then in `populateRow` you could do something like this:

```fs
// ...
| SqlValue.Custom (value, fn) -> 
    let sqlParam = cmd.Parameters.AddWithValue(paramName, value)
    fn sqlParam
```

The drawback to this is that we lose the convenience of the `SqlRow` and `SqlValue` types, instead having to add each TVP row as regular .NET types. 

I'd be happy to create a pull request for this feature, but I wanted to see if you had feedback and if it's something you're interested in adding to the package first.

**Comment by Zaid-Ajaj** [comment]
Hello @nozzlegear, thanks a lot for the great analysis and suggestions. To be honest, I think using this case would make things a lot easier:
```fs
type SqlValue = 
  | Table of string * DataTable
```
This way, we have the user take care of how to create and populate a `DataTable` without needing the recursion in type definitions. Then, the `populate` function would be implemented as follows;
```fs
| SqlValue.Table (typeName, dataTable) -> 
    let tableParameter = cmd.Parameters.AddWithValue(paramName, dataTable)
    // TypeName must be set to the custom SQL tvp type 
    tableParameter.TypeName <- typeName
    // SqlDbType must be set to Structured for a TVP parameter
    tableParameter.SqlDbType <- SqlDbType.Structured
```
What do you think about this implementation?

**Comment by nozzlegear** [comment]
I agree, that works perfectly! I'd be happy to send a pull request for it some time tomorrow, if you'd like?

**Comment by Zaid-Ajaj** [comment]
A PR would be great!
