### ISSUE TITLE
Add support for a list of parameters

### ISSUE THREAD

**Issue by tforkmann** [Zaid-Ajaj/DustyTables#9]
**Is your feature request related to a problem? Please describe.**
I often need to filter a list of ids in my querys. I usally use the IN operator for tjat
**Describe the solution you'd like**
Hey Zaid,

I would like to add a list type for the SqlValue like this:

```fs
type SqlValue =
    | TinyInt of uint8
    | TinyIntList of seq<uint8>
```
and then add the list of parameters like this:

```fs
let addValues list =
   list
   |> Seq.map (fun x -> cmd.Parameters.AddWithValue(sprintf "%s%A" paramName x, x))
   |> Seq.toArray
   |> ignore
match snd param with
| SqlValue.IntList list -> list |> addValues
| SqlValue.TinyIntList list -> list |> addValues
```

You have to adjust the query string as well.
This could be done like this:

```fs
let createSkalarString list parameterName =
    list |> Seq.map (fun x -> sprintf "@%s%A" parameterName x) |> String.concat ","
let skalarString = Sql.createSkalarString aggregationTypes "types"
````
This works is my test case and I have a PR ready just let me know if this solution would be ok for you.

**Comment by Zaid-Ajaj** [comment]
Hello @tforkmann, in order to fix this issue and #10, I would rather resolve #8 first (v2.0 roadmap) which makes the API a lot easier to use and makes it easy to fix both of your issue, if you are would like to give that issue a try it would be great because I don't think I want to build upon this API anymore

**Comment by Zaid-Ajaj** [comment]
@tforkmann v2.0 has been released and now makes it possible for users to add a custom `SqlParameter` using the `Sql.parameter yourParameterHere` function when providing the list of parameters

**Comment by tforkmann** [comment]
Hi Zaid,

i was able to get it working!

This is what I did:

```fs
open Microsoft.Data.SqlClient
type FilterList =  {
    Parameters : list<string * SqlParameter>
    ParameterString : string
}
let createTinyIntParameterList (parameterName,value:byte,iteration) =
    let parameter = SqlParameter()
    parameter.SqlDbType <- SqlDbType.TinyInt
    parameter.Value <- value
    sprintf "@%s%i" parameterName iteration,parameter

let getSelectedAggregationTypes =
    let aggregationTypes = [9uy;10uy;11uy;15uy]
    let parameters =
        aggregationTypes
        |> List.mapi (fun i atyp ->
            createTinyIntParameterList ("atyp",atyp,i))

    let filters = {
        Parameters = parameters
        ParameterString = parameters |> List.map fst |> String.concat ","
    }
    let query =
        sprintf
            """
            select aggregattype.AggregatTyp_ID,aggregattype.AggregatTyp
            from Alle.DomAggregatTyp as aggregattype
            where aggregattype.AggregatTyp_ID IN (%s) """ filters.ParameterString
    printfn "Query %A" query
    connectionString()
    |> Sql.connect
    |> Sql.query query
    |> Sql.parameters filters.Parameters
    |> Sql.executeAsync (fun read ->
        {|
            date = read.tinyint "AggregatTyp_ID"
            Amount = read.string "AggregatTyp"
         |})
    |> Async.RunSynchronously
```

**Comment by Zaid-Ajaj** [comment]
It seems a bit too complicated 🤔 here is my attempts to simplify this:
```fs
let getSelectedAggregationTypes =
    let aggregationTypes = [9uy;10uy;11uy;15uy]
    let serializedTypes = aggregationTypes |> List.map string |> String.concat ","
    let query =
      """
       select aggregattype.AggregatTyp_ID,aggregattype.AggregatTyp
       from Alle.DomAggregatTyp as aggregattype
       where aggregattype.AggregatTyp_ID IN (SELECT CAST(value as tinyint) FROM SPLIT_STRING(@ids, ',')) 
      """
    printfn "Query %A" query

    connectionString()
    |> Sql.connect
    |> Sql.query query
    |> Sql.parameters [ "@ids", Sql.string serializedTypes ]
    |> Sql.execute (fun read ->
        {|
            date = read.tinyint "AggregatTyp_ID"
            Amount = read.string "AggregatTyp"
         |})
```
Of course, I can't test this on my machine but I think you get the general idea :smile: 

Please let me know if the issue is resolved with this, thanks!

**Comment by tforkmann** [comment]
Hi Zaid,

this would work fine if your SQL database has a compatibility_level>= 130.
I'm ok for now. Just wanted to give that feedback.

**Comment by Zaid-Ajaj** [comment]
> this would work fine if your SQL database has a compatibility_level>=130.

I haven't worked with T-SQL for a while so I tend to forget these annoying stuff 😓 Anyways I am glad you got it working :100:
